### ISSUE TITLE
Forbidden - CSRF token invalid

### ISSUE THREAD

**Issue by alsifius** [ubccr/mokey#10]
Any attempt to move beyond the initial login page produces this error. Beyond help with the error, a log file describing problem and pointing to possible resolutions would be a big help.

**Comment by aebruno** [comment]
Did you recently upgrade mokey? Try clearing out your browser cookies (or at least the cookies for mokey) and the re-logging in. The more recent versions had changes to the way cookies were stored.

**Comment by rudgab** [comment]
I'm having the same problems. This:

level=error msg="logouthandler: failed to save session" error="securecookie: error - caused by: crypto/aes: invalid key size 29"

occurs in the log. Maybe it is related to the AES size in java: but my mokey.jaml is set to:

#------------------------------------------------------------------------------
# Authentication key used for HMAC token signing and secure cookies
#------------------------------------------------------------------------------
auth_key: "32 or 64 bytes random key"

#------------------------------------------------------------------------------
# Encryption key used for encrypting cookies
#------------------------------------------------------------------------------
enc_key: "16, 24, or 32 byte random key"

Don't know what to do, any idea?

**Comment by aebruno** [comment]
You need to change those values. They are just defaults. For example:
```
enc_key: "2dc2aadf63c392585eef7289709932ca"
```

DO NOT actually use the above. It is just an example. Need to generate your own random key of either 16, 24, or 32 bytes.

**Comment by rudgab** [comment]
Thanks, that made the error gone.

Unfortunately I can only login with admin, any user is forbidden by:
IPA login failed with HTTP status code: 401" uid=…
even when I reset a new password to the user.

Regards,

Rudi Gabler

**Comment by aebruno** [comment]
> Unfortunately I can only login with admin, any user is forbidden by

Did you setup a role in freeipa for mokey? See around the third paragraph of the install file:

https://github.com/ubccr/mokey#install

**Comment by rudgab** [comment]
Hi,

yes I did this. It has something to do with the users. When I remove the user and recreate it,  it works. At least this is a workaround.

Regards,

Rudi Gabler
