### ISSUE TITLE
FreeIPA+Mokey+Hydra docker-compose

### ISSUE THREAD

**Issue by jvinolas** [ubccr/mokey#74]
If anyone finds it useful we are developing an OpenID based on FreeIPA+Mokey+Hydra easy and quick to set up using docker-compose. You can find it at https://gitlab.com/isard/isard-openid

Many bugs still there to be fixed but it is working now. Feel free to open us issues if you try it.

**Comment by aebruno** [comment]
This looks great! Thanks for sharing.

**Comment by zem** [comment]
I have spend some work as well based on this compose file, you can find it here: 
https://git.conesphere.cloud/conesphere/podman/hub/mokey 
and here https://git.conesphere.cloud/conesphere/podman/hub/freeipa

it is using my own Interpretation of podman container orchestration instead of docker-compose available here https://git.conesphere.cloud/conesphere/podman/tools/podman_tools

I may point out that the registration of the container to ipa does not seem to be necessary at the moment.
As far as I can tell,  the container only needs a valid keytab file, which can be generated on any ipa host, and the ipa ca certificate.
